import mongoose from "mongoose";
const DaysheetSchema = new mongoose.Schema(
  {
    
    store:{ type: String,required:true},
    date:{type:Date,required:true},
    dateFormat:{type:String,required:true},
    shop:{type:String,required:true},
    image:{type:String},
    purchaseimage:{type:String},
    n50:{type:Number, required:true,default:0},
    n20:{type:Number, required:true,default:0},
    n10:{type:Number, required:true,default:0},
    n5:{type:Number, required:true,default:0},
    n2:{type:Number, required:true,default:0},
    n1:{type:Number, required:true,default:0},
    n50p:{type:Number, required:true,default:0},
    n20p:{type:Number, required:true,default:0},
    n10p:{type:Number, required:true,default:0},
    n5p:{type:Number, required:true,default:0},
    n2p:{type:Number, required:true,default:0},
    n1p:{type:Number, required:true,default:0},
    n50t:{type:Number, required:true,default:0},
    n20t:{type:Number, required:true,default:0},
    n10t:{type:Number, required:true,default:0},
    n5t:{type:Number, required:true,default:0},
    n2t:{type:Number, required:true,default:0},
    n1t:{type:Number, required:true,default:0},
    n50pt:{type:Number, required:true,default:0},
    n20pt:{type:Number, required:true,default:0},
    n10pt:{type:Number, required:true,default:0},
    n5pt:{type:Number, required:true,default:0},
    n2pt:{type:Number, required:true,default:0},
    n1pt:{type:Number, required:true,default:0},
    subtotal:{type:Number, required:true},
    yesfloat:{type:Number, required:true},
    cashsale:{type:Number, required:true},
    todayfloat:{type:Number, required:true},
    tillcash:{type:Number, required:true},
    card:{type:Number, required:true},
    storesales:{type:Number, required:true},
  diff:{type:Number, required:true},
  pettycash:{type:Number, required:true},
  cashmanag:{type:Number, required:true},
  websiteOrders:{type:Number},
  justeatOrders:{type:Number},
  deliverOrders:{type:Number},
  ubereatOrders:{type:Number},
  websiteTotal:{type:Number},
  deliverTotal:{type:Number},
  justeatTotal:{type:Number},
  ubereatTotal:{type:Number},
  onlineTotal:{type:Number},
  onlineOrders:{type:Number},
  totalSales:{type:Number},
  wastages:[{
    itemmaterial:{type:String},
    item:{type:String},
    quantity:{type:Number},
    reason:{type:String},
    totalprice:{type:Number}
  }],
  purchases:[{
    purchase:{type:String},
    amount:{type:Number}
  }],
  bagprice1:{type:Number},
  bagprice2:{type:Number},
  bagprice3:{type:Number},
  bagprice4:{type:Number},
  goodToGoTotal:{type:Number},
  bagprice5:{type:String},
  contents1:{type:String},
  contents2:{type:String},
  contents3:{type:String},
  contents4:{type:String},
  contents5:{type:String},
  bagid1:{type:String},
  bagid2:{type:String},
  bagid3:{type:String},
  bagid4:{type:String},
  bagid5:{type:String},
  otherinfo:{type:String},
  verified:{type:Boolean, default:false},
  isSubmitted:{type:Boolean, default:false},
  comment:{type:String},
  submittedBy:{type:String, required:true},
  ispettycash:{type:Boolean, default:false},
  iscashsale:{type:Boolean, default:false},
  iscard:{type:Boolean, default:false},
  isstoresale:{type:Boolean, default:false},
  issubtotal:{type:Boolean, default:false},
  iscashmanag:{type:Boolean, default:false},
  istodayfloat:{type:Boolean, default:false},
  istotalSales:{type:Boolean, default:false}
  },
  { timestamps: true }
);

export default mongoose.model("Daysheet", DaysheetSchema)
